spring:
    datasource:
        #type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
        #hikari:
        type: com.alibaba.druid.pool.DruidDataSource
liquibase:
    change-log: classpath:/liquibase/master.xml
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    enabled: true
    drop-first: false
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.taikang.test.sqltest