server:
  port: 8089
  tomcat:
    uri-encoding: UTF-8

#spring config
spring:
  application:
    name: iams
  profiles:
    active: dev

  cache:
    #guava或者redis，若是redis，需要配置
    type: redis
    cacheNames:
      dbmeta: 86400
      auth: 86400
      accessToken: 86400
      loginErrorNumPerHourPerId: 3600
      loginErrorNumPerDayPerIP: 86400
      userIdLocked: 10800
      userIPLocked: 86400
      ldapLoginUser: 1800

  aop:
    #proxy-target-class: true
    auto: true

# MyBatis
mybatis:
  mapper-locations: mapper/*.xml,classpath*:com/taikang/**/mapper/*.xml
  #config-location: classpath:config/mybatis-config.xml
  typeHandlersPackage: com.taikang.health.iams.dao

health:
  application:
    name: iams
    version: 1.0.0
    comment: 身份认证系统
    website: www.taikang.com
  #开启访问日志:slf4j、rdb
  access-logger: rdb

login:
  #每个ID每小时登陆失败超过（？）（包含）账号被锁定3小时
  loginErrorNumPerHourPerId: 4
  #每个IP每天登陆失败超过（？）次（包含）IP被锁定24小时
  loginErrorNumPerDayPerIP: 50

oauth2:
  access_token:
    expiresIn: 86400
  refresh_token:
    expiresIn: 86400